In [2]:
import numpy as np

# Datatypes and Attribut

In [3]:
# Numpy's min datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [ ]:
# voir la dimensio d'un array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5