In [1]:
import numpy as np

# Datatypes and Attribut

In [2]:
# Numpy's min datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
# voir la dimensio d'un array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [10]:
import pandas as pd

df = pd.DataFrame(a2)

In [11]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating array

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int32')

In [14]:
ones = np.ones((2,3))

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0,10,2)

In [21]:
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[4, 7, 4, 2, 6],
       [3, 6, 4, 2, 8],
       [0, 8, 9, 1, 1]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5,3))

In [27]:
random_array_2

array([[0.21226423, 0.67349707, 0.93943033],
       [0.492223  , 0.16553443, 0.87823971],
       [0.41775333, 0.85243698, 0.1239275 ],
       [0.55631853, 0.10756071, 0.96155017],
       [0.49397268, 0.75984844, 0.26779713]])

In [28]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[3.27850687e-01, 7.17225794e-01, 7.75039030e-01],
       [8.52968401e-01, 9.35275418e-01, 2.84737769e-01],
       [2.37961599e-01, 8.67259515e-01, 7.37794985e-01],
       [2.35673341e-01, 1.61987326e-03, 4.93617749e-01],
       [8.34277275e-01, 7.99648880e-04, 2.95409284e-01]])

In [41]:
np.random.seed(seed=42)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [49]:
np.random.seed(7)
random_array_5 = np.random.random(size=(5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])